version: "3"
services:
  yarp-rev-proxy:
    image: agilewaysreg.azurecr.io/sidecar/proxy:1.1
    container_name: yarp
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host

  simple-server:
    image: agilewaysreg.azurecr.io/sidecar/server:1.2
    container_name: server
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
